


#ifndef _TECHLIB_COLOR_H
#define _TECHLIB_COLOR_H 1

#if defined(TECHLIB_WINDOWS) && !defined(TECHLIB_LINUX)
	#include <windows.h>
	
	WORD WHITE_B = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY;
	WORD WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
	WORD BLACK_B = 0;


	WORD LGRAY_B = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE;
	WORD GRAY_B = BACKGROUND_INTENSITY;
	WORD GRAY = FOREGROUND_INTENSITY;
	WORD LGRAY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE;

	WORD BLUE_B = BACKGROUND_BLUE;
	WORD BLUE = FOREGROUND_BLUE;
	WORD LBLUE_B = BACKGROUND_BLUE | BACKGROUND_INTENSITY;
	WORD LBLUE = FOREGROUND_BLUE | FOREGROUND_INTENSITY;
	
	WORD GREEN_B = BACKGROUND_GREEN;
	WORD GREEN = FOREGROUND_GREEN;
	WORD LGREEN_B = BACKGROUND_GREEN | BACKGROUND_INTENSITY;
	WORD LGREEN = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
	
	WORD RED_B = BACKGROUND_RED;
	WORD RED = FOREGROUND_RED;
	WORD LRED_B = BACKGROUND_RED | BACKGROUND_INTENSITY;
	WORD LRED = FOREGROUND_RED | FOREGROUND_INTENSITY;
	
	WORD AQUA_B = BACKGROUND_BLUE | BACKGROUND_GREEN;
	WORD AQUA = FOREGROUND_BLUE | FOREGROUND_GREEN;
	WORD LAQUA_B = BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY;
	WORD LAQUA = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY;	
	
	WORD YELLOW_B = BACKGROUND_RED | BACKGROUND_GREEN;
	WORD YELLOW = FOREGROUND_RED | FOREGROUND_GREEN;
	WORD LYELLOW_B = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY;
	WORD LYELLOW = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY;	
	
	WORD PURPLE_B = BACKGROUND_RED | BACKGROUND_BLUE;
	WORD PURPLE = FOREGROUND_RED | FOREGROUND_BLUE;
	WORD LPURPLE_B = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY;
	WORD LPURPLE = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY;

    void color(WORD color){
        HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
        SetConsoleTextAttribute(hConsole, color);
        return;
    }
	
#endif
#if defined(TECHLIB_LINUX) && !defined(TECHLIB_WINDOWS)

	#define COLOR "\033["
	#define RESET "0;"
	#define BOLD "1;"
	#define UNDERLINE "4;"
	#define INVERSE "7;"
	#define BOLDOFF "21;"
	#define UNDERLINEOFF "24;"
	#define INVERSEOFF "27;"
	#define CLEAR "\033[0m"
	
	#define BLACK "30m"
	#define RED "31m"
	#define GREEN "32m"
	#define YELLOW "33m"
	#define BLUE "34m"
	#define MAGENTA "35m"
	#define CYAN "36m"
	#define WHITE "37m"
	
	#define BLACK_B "40;"
	#define RED_B "41;"
	#define GREEN_B "42;"
	#define YELLOW_B "43;"
	#define BLUE_B "44;"
	#define MAGENTA_B "45;"
	#define CYAN_B "46;"
	#define WHITE_B "47;"
	#define GRAY_B "100;"
	#define LRED_B "101;"
	#define LGREEN_B "102;"
	#define LYELLOW_B "103;"
	#define LBLUE_B "104;"
	#define LPURPLE "105;"
	#define TEAL_B "106;"
	
#endif


#endif